USE HOSPITAL_OTOCLINICA;

CREATE TABLE MEDICO
(CRM                INT           NOT NULL,
NOME                VARCHAR(100)  NOT NULL,
CPF                 VARCHAR(15)   NOT NULL,
RG                  VARCHAR(15),
DATA_NASCIMENTO     DATETIME,
ENDERECO            VARCHAR(100),
TELEFONE            VARCHAR(15),
SEXO                CHAR(1),
COD_ESPECIALIDADE   INT,
COD_PRESTADOR       INT,
                    CONSTRAINT PK_MEDICO
				    PRIMARY KEY(CRM)
);

CREATE TABLE ENFERMEIRO
(COREN              INT           NOT NULL,
NOME                VARCHAR(100)  NOT NULL,
CPF                 VARCHAR(15)   NOT NULL,
RG                  VARCHAR(15),
DATA_NASCIMENTO     DATETIME,
ENDERECO            VARCHAR(100),
TELEFONE            VARCHAR(15),
SEXO                CHAR(1),
COD_ESPECIALIDADE   INT,
COD_PRESTADOR       INT,
COD_SETOR           INT,
                    CONSTRAINT PK_ENFERMEIRO
				    PRIMARY KEY(COREN)
);

CREATE TABLE TECNICO_ENFERMAGEM
(COREN              INT           NOT NULL,
NOME                VARCHAR(100)  NOT NULL,
CPF                 VARCHAR(15)   NOT NULL,
RG                  VARCHAR(15),
DATA_NASCIMENTO     DATETIME,
ENDERECO            VARCHAR(100),
TELEFONE            VARCHAR(15),
SEXO                CHAR(1),
COD_ESPECIALIDADE   INT,
COD_PRESTADOR       INT,
COD_SETOR           INT,
                CONSTRAINT PK_TECNICO_ENFERMAGEM
				PRIMARY KEY(COREN)
);

CREATE TABLE ESPECIALIDADE
(COD_ESPECIALIDADE           INT          NOT NULL,
NOME_ESPECIALIDADE           VARCHAR(50)  NOT NULL,
                             CONSTRAINT PK_ESPECIALIDADE
							 PRIMARY KEY(COD_ESPECIALIDADE)
);

CREATE TABLE MEDICO_ESPECIALIDADE
(CRM_MEDICO          INT    NOT NULL,
COD_ESPECIALIDADE    INT    NOT NULL,
                     CONSTRAINT PK_MEDICO_ESPECIALIDADE
					 PRIMARY KEY(CRM_MEDICO, COD_ESPECIALIDADE),
					 CONSTRAINT FK_MEDICO_ESPECIALIDADE
					 FOREIGN KEY (CRM_MEDICO) REFERENCES MEDICO(CRM),
					 CONSTRAINT FK_MEDICO_ESPECIALIDADE_ESPECIALIDADE
					 FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE (COD_ESPECIALIDADE)
);

ALTER TABLE MEDICO
ADD CONSTRAINT ESPECIALIDADE_MEDICO
FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE (COD_ESPECIALIDADE);

ALTER TABLE ENFERMEIRO
ADD CONSTRAINT ESPECIALIDADE_ENFERMEIRO
FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE (COD_ESPECIALIDADE);

ALTER TABLE TECNICO_ENFERMAGEM
ADD CONSTRAINT ESPECIALIDADE_TECNICO_ENFERMAGEM
FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE (COD_ESPECIALIDADE);


CREATE TABLE PRESTADOR
(COD_PRESTADOR      INT         NOT NULL,
COMPLEMENTO         VARCHAR(50) NOT NULL,
                   CONSTRAINT PK_PRESTADOR
				   PRIMARY KEY (COD_PRESTADOR)
);

ALTER TABLE MEDICO
ADD CONSTRAINT PRESTADOR_MEDICO
FOREIGN KEY (COD_PRESTADOR) REFERENCES PRESTADOR(COD_PRESTADOR);

ALTER TABLE ENFERMEIRO
ADD CONSTRAINT PRESTADOR_ENFERMEIRO
FOREIGN KEY (COD_PRESTADOR) REFERENCES PRESTADOR(COD_PRESTADOR);

ALTER TABLE TECNICO_ENFERMAGEM
ADD CONSTRAINT PRESTADOR_TECNICO_ENFERMAGEM
FOREIGN KEY (COD_PRESTADOR) REFERENCES PRESTADOR(COD_PRESTADOR);

CREATE TABLE PACIENTE
(CPF            VARCHAR(15)   NOT NULL,
NOME            VARCHAR(100)  NOT NULL,
RG              VARCHAR(15),
DATA_NASCIMENTO DATETIME,
TELEFONE        VARCHAR(15),
ENDERECO        VARCHAR(100),
SEXO            CHAR(1),
COD_PLANO       INT,
NUMERO_CARTEIRA VARCHAR(15),
COD_SETOR       INT,
                CONSTRAINT PK_PACIENTE
		        PRIMARY KEY(CPF)
);

CREATE TABLE PLANO_SAUDE
(COD_PLANO         INT         NOT NULL,
NOME_PLANO         VARCHAR(50) NOT NULL,
                   CONSTRAINT PK_PLANO_SAUDE
				   PRIMARY KEY(COD_PLANO)
);

CREATE TABLE CARTEIRA_CONVENIO
(NUMERO_CARTEIRA        VARCHAR(15)     NOT NULL,
NOME_CARTEIRA           VARCHAR(100)    NOT NULL,
VALIDADE                DATETIME,
CATEGORIA               VARCHAR(20),
ACOMODACAO              VARCHAR(50),
PATROCINADOR            VARCHAR(20),
DISPONIBILIDADE         VARCHAR(20),
COD_PLANO               INT,
                        CONSTRAINT PK_CARTEIRA_CONVENIO
						PRIMARY KEY(NUMERO_CARTEIRA),
						CONSTRAINT CARTEIRA_CONVENIO_PLANO_SAUDE
						FOREIGN KEY(COD_PLANO) REFERENCES PLANO_SAUDE(COD_PLANO)
);

ALTER TABLE PACIENTE
ADD CONSTRAINT FK_PACIENTE_PLANO_SAUDE
FOREIGN KEY (COD_PLANO) REFERENCES PLANO_SAUDE(COD_PLANO);

ALTER TABLE PACIENTE 
ADD CONSTRAINT FK_PACIENTE_CARTEIRA_CONVENIO
FOREIGN KEY (NUMERO_CARTEIRA) REFERENCES CARTEIRA_CONVENIO(NUMERO_CARTEIRA);


CREATE TABLE CIRURGIA
(COD_CIRURGIA             INT       NOT NULL,
DATA_CIRURGIA             DATETIME,
CPF_PACIENTE              VARCHAR(15),
CRM_MEDICO                INT,
COREN_ENFERMEIRO          INT,
COREN_TECNICO_ENFERMAGEM  INT,
NUMERO_SALA               INT,
                          CONSTRAINT PK_CIRURGIA
					      PRIMARY KEY(COD_CIRURGIA),
					      CONSTRAINT FK_CIRURGIA_MEDICO
					      FOREIGN KEY(CRM_MEDICO) REFERENCES MEDICO(CRM),
					      CONSTRAINT FK_CIRURGIA_PACIENTE
					      FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF),
					      CONSTRAINT FK_CIRURGIA_ENFERMEIRO
					      FOREIGN KEY(COREN_ENFERMEIRO) REFERENCES ENFERMEIRO(COREN),
						  CONSTRAINT FK_CIRURGIA_TENICO_ENFERMAGEM
						  FOREIGN KEY(COREN_TECNICO_ENFERMAGEM) REFERENCES TECNICO_ENFERMAGEM(COREN)
);

CREATE TABLE SALA_CENTRO_CIRURGICO
(NUMERO_SALA           INT         NOT NULL,
COD_ESPECIALIDADE      INT         NOT NULL,
                       CONSTRAINT PK_SALA_CENTRO_CIRURGICO
					   PRIMARY KEY(NUMERO_SALA)
);

CREATE TABLE SALA_CC_ESPECIALIDADE
(COD_ESPECIALIDADE        INT         NOT NULL,
NOME_ESPECIALIDADE        VARCHAR(50) NOT NULL,
                          CONSTRAINT SALA_CC_ESPECIALIDADE
						  PRIMARY KEY(COD_ESPECIALIDADE)
);

ALTER TABLE SALA_CENTRO_CIRURGICO
ADD CONSTRAINT FK_SALA_CC_ESPECIALIDADE
FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES SALA_CC_ESPECIALIDADE(COD_ESPECIALIDADE);

ALTER TABLE CIRURGIA
ADD CONSTRAINT FK_SALA_CENTRO_CIRURGICO_CIRURGIA
FOREIGN KEY(NUMERO_SALA) REFERENCES SALA_CENTRO_CIRURGICO(NUMERO_SALA);

CREATE TABLE EXAME
(COD_EXAME                INT          NOT NULL,
NOME_EXAME                VARCHAR(100) NOT NULL,
DATA_EXAME                DATETIME     NOT NULL,
COREN_ENFERMEIRO          INT,
COREN_TECNICO_ENFERMAGEM  INT,
CRM_MEDICO                INT,
COD_ESPECILIDADE_EXAME    INT,
CPF_PACIENTE              VARCHAR(15),
                          CONSTRAINT PK_EXAME
						  PRIMARY KEY(COD_EXAME),
						  CONSTRAINT FK_EXAME_ENFERMEIRO
						  FOREIGN KEY(COREN_ENFERMEIRO) REFERENCES ENFERMEIRO(COREN),
						  CONSTRAINT FK_EXAME_TECNICO_ENFERMAGEM
						  FOREIGN KEY(COREN_TECNICO_ENFERMAGEM) REFERENCES TECNICO_ENFERMAGEM(COREN),
						  CONSTRAINT FK_EXAME_MEDICO
						  FOREIGN KEY(CRM_MEDICO) REFERENCES MEDICO(CRM),
						  CONSTRAINT FK_EXAME_PACIENTE
						  FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE ESPECIALIDADE_EXAME
(COD_ESPECIALIDADE         INT          NOT NULL,
NOME_ESPECIALIDADE         VARCHAR(100) NOT NULL,
                           CONSTRAINT PK_ESPECIALIDADE_EXAME
						   PRIMARY KEY(COD_ESPECIALIDADE)
);

CREATE TABLE EXAME_ESPECIALIDADE
(COD_EXAME         INT   NOT NULL,
COD_ESPECIALIDADE  INT   NOT NULL,
                   CONSTRAINT PK_EXAME_ESPECIALIDADE
				   PRIMARY KEY(COD_EXAME, COD_ESPECIALIDADE),
				   CONSTRAINT FK_EXAME_ESPECIALIDADE_EXAME
				   FOREIGN KEY(COD_EXAME) REFERENCES EXAME(COD_EXAME),
				   CONSTRAINT FK_EXAME_ESPECIALIDADE_ESPECIALIDADE
				   FOREIGN KEY(COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE_EXAME(COD_ESPECIALIDADE)
);

CREATE TABLE FUNCIONARIO
(MATRICULA              INT             NOT NULL,
CPF                     VARCHAR(15)     NOT NULL,
RG                      VARCHAR(15),
NOME                    VARCHAR(100),
DATA_NASCIMENTO         DATETIME,
ENDERECO                VARCHAR(100),
SEXO                    CHAR(1),
TELEFONE                VARCHAR(15),
COD_SETOR               INT,
COD_EMPRESA             INT,
                        CONSTRAINT PK_FUNCIONARIO
						PRIMARY KEY(MATRICULA)
);

CREATE TABLE SETOR
(COD_SETOR            INT           NOT NULL,
NOME_SETOR            VARCHAR(100)  NOT NULL,
                      CONSTRAINT PK_SETOR
					  PRIMARY KEY(COD_SETOR)
);

ALTER TABLE PACIENTE
ADD CONSTRAINT FK_SETOR_PACIENTE
FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR);

ALTER TABLE ENFERMEIRO
ADD CONSTRAINT FK_ENFERMEIRO_SETOR
FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR);

ALTER TABLE TECNICO_ENFERMAGEM
ADD CONSTRAINT FK_TECNICO_ENFERMAGEM_SETOR
FOREIGN KEY(COD_SETOR) REFERENCES SETOR(COD_SETOR);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_SETOR
FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR);

CREATE TABLE MEDICAMENTO
(COD_MEDICAMENTO       INT         NOT NULL,
NOME_MEDICAMENTO       VARCHAR(50) NOT NULL,
DOSAGEM                INT,
VALIDADE               DATETIME,
LABORATORIO            VARCHAR(100),
                       CONSTRAINT PK_MEDICAMENTO
					   PRIMARY KEY(COD_MEDICAMENTO)
);

CREATE TABLE PACIENTE_MEDICAMENTO
(COD_MEDICAMENTO    INT             NOT NULL,
CPF_PACIENTE        VARCHAR(15),
DOSAGEM             INT,
                    CONSTRAINT PK_PACIENTE_MEDICAMENTO
					PRIMARY KEY(CPF_PACIENTE, COD_MEDICAMENTO),
					CONSTRAINT FK_PACIENTE_MEDICAMENTO_PACIENTE
					FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF),
					CONSTRAINT FK_PACIENTE_MEDICAMENTO_MEDICAMENTO
					FOREIGN KEY(COD_MEDICAMENTO) REFERENCES MEDICAMENTO(COD_MEDICAMENTO)
);


CREATE TABLE PACIENTE_CIRURGIA
(CPF_PACIENTE          VARCHAR(15)    NOT NULL,
COD_CIRURGIA           INT            NOT NULL,
                       CONSTRAINT PK_PACIENTE_CIRURGIA
					   PRIMARY KEY(CPF_PACIENTE, COD_CIRURGIA),
					   CONSTRAINT FK_PACIENTE_CIRURGIA_PACIENTE
					   FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF),
					   CONSTRAINT FK_PACIENTE_CIRURGIA_CIRURGIA
					   FOREIGN KEY(COD_CIRURGIA) REFERENCES CIRURGIA(COD_CIRURGIA)
);

CREATE TABLE PACIENTE_EXAME
(CPF_PACIENTE          VARCHAR(15)    NOT NULL,
COD_EXAME              INT            NOT NULL,
                       CONSTRAINT PK_PACIENTE_EXAME
					   PRIMARY KEY(CPF_PACIENTE, COD_EXAME),
					   CONSTRAINT FK_PACIENTE_EXAME_PACIENTE
                       FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF),
					   CONSTRAINT FK_PACIENTE_EXAME_EXAME
					   FOREIGN KEY (COD_EXAME) REFERENCES EXAME(COD_EXAME)
);

CREATE TABLE PRESCRICAO
(COD_PRESCRICAO           INT       NOT NULL,
CRM_MEDICO                INT,
COREN_ENFERMEIRO          INT,
COREN_TECNICO_ENFERMAGEM  INT,
CPF_PACIENTE              VARCHAR(15),
                          CONSTRAINT PK_PRESCRICAO
						  PRIMARY KEY(COD_PRESCRICAO),
						  CONSTRAINT FK_PRESCRICAO_MEDICO
						  FOREIGN KEY(CRM_MEDICO) REFERENCES MEDICO(CRM),
						  CONSTRAINT FK_PRESCRICAO_ENFERMEIRO
						  FOREIGN KEY(COREN_ENFERMEIRO) REFERENCES ENFERMEIRO(COREN),
						  CONSTRAINT FK_PRESCRICAO_TECNICO_ENFERMAGEM
						  FOREIGN KEY(COREN_TECNICO_ENFERMAGEM) REFERENCES TECNICO_ENFERMAGEM(COREN),
						  CONSTRAINT FK_PRESCRICAO_PACIENTE
						  FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE PRONTUARIO_ELETRONICO
(COD_PRONTUARIO_ELETRONICO             INT        NOT NULL,
CRM_MEDICO                INT,
COREN_ENFERMEIRO          INT,
COREN_TECNICO_ENFERMAGEM  INT,
CPF_PACIENTE              VARCHAR(15),
                          CONSTRAINT PK_PRONTUARIO_ELETRONICO
						  PRIMARY KEY(COD_PRONTUARIO_ELETRONICO),
						  CONSTRAINT FK_PEP_MEDICO
						  FOREIGN KEY(CRM_MEDICO) REFERENCES MEDICO(CRM),
						  CONSTRAINT FK_PEP_ENFERMEIRO
						  FOREIGN KEY(COREN_ENFERMEIRO) REFERENCES ENFERMEIRO(COREN),
						  CONSTRAINT FK_PEP_TECNICO_ENFERMAGEM
						  FOREIGN KEY(COREN_TECNICO_ENFERMAGEM) REFERENCES TECNICO_ENFERMAGEM(COREN),
						  CONSTRAINT FK_PEP_PACIENTE
						  FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE INTERNACAO
(COD_INTERNACAO         INT          NOT NULL,
CPF_PACIENTE            VARCHAR(15),
DATA_INTERNACAO         DATETIME,
DATA_ALTA               DATETIME,
NUMERO_APARTAMENTO      INT,
NUMERO_LEITO_ENFERMARIA INT,
NUMERO_LEITO_UTI        INT,
NUMERO_LEITO_CTI        INT,
                        CONSTRAINT PK_INTERNACAO
						PRIMARY KEY(COD_INTERNACAO),
						CONSTRAINT FK_PACIENTE_INTERNACAO
						FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE APARTAMENTO
(NUMERO_APARTAMENTO       INT      NOT NULL,
COD_SETOR                 INT,
                          CONSTRAINT PK_APARTAMENTO
						  PRIMARY KEY(NUMERO_APARTAMENTO),
						  CONSTRAINT FK_APARTAMENTO_SETOR
						  FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

CREATE TABLE ENFERMARIA
(NUMERO_LEITO_ENFERMARIA INT        NOT NULL,
COD_SETOR                INT,
                         CONSTRAINT PK_ENFERMARIA
						 PRIMARY KEY(NUMERO_LEITO_ENFERMARIA),
						 CONSTRAINT FK_ENFERMARIA_SETOR
						 FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

CREATE TABLE UTI
(NUMERO_LEITO_UTI             INT   NOT NULL,
COD_SETOR                     INT,
                              CONSTRAINT PK_UTI
						      PRIMARY KEY(NUMERO_LEITO_UTI),
							  CONSTRAINT FK_UTI_SETOR
						      FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

CREATE TABLE CTI
(NUMERO_LEITO_CTI         INT    NOT NULL,
COD_SETOR                 INT,
                          CONSTRAINT PK_CTI
						  PRIMARY KEY(NUMERO_LEITO_CTI),
						  CONSTRAINT FK_CTI_SETOR
						  FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

ALTER TABLE INTERNACAO
ADD CONSTRAINT FK_APARTAMENTO_INTERNACAO
FOREIGN KEY(NUMERO_APARTAMENTO) REFERENCES APARTAMENTO(NUMERO_APARTAMENTO);

ALTER TABLE INTERNACAO
ADD CONSTRAINT FK_UTI_INTERNACAO
FOREIGN KEY(NUMERO_LEITO_UTI) REFERENCES UTI(NUMERO_LEITO_UTI);

ALTER TABLE INTERNACAO
ADD CONSTRAINT FK_CTI_INTERNACAO
FOREIGN KEY(NUMERO_LEITO_CTI) REFERENCES CTI(NUMERO_LEITO_CTI);

ALTER TABLE INTERNACAO
ADD CONSTRAINT FK_ENFERMARIA_INTERNACAO
FOREIGN KEY(NUMERO_LEITO_ENFERMARIA) REFERENCES ENFERMARIA(NUMERO_LEITO_ENFERMARIA);

CREATE TABLE ATENDIMENTO
(COD_ATENDIMENTO        INT       NOT NULL,
DATA_ATENDIMENTO        DATETIME  NOT NULL,
CPF_PACIENTE            VARCHAR(15),
                        CONSTRAINT PK_ATENDIMENTO
						PRIMARY KEY(COD_ATENDIMENTO),
						CONSTRAINT FK_ATENDIMENTO_PACIENTE
						FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE OBITUARIO
(COD_OBITUARIO          INT       NOT NULL,
DATA_OBITO              DATETIME,
CAUSA_OBITO             VARCHAR(100),
CPF_PACIENTE            VARCHAR(15),
                        CONSTRAINT PK_OBITUARIO
						PRIMARY KEY(COD_OBITUARIO),
						CONSTRAINT FK_OBITUARIO_PACIENTE
						FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE CONSULTA
(COD_CONSULTA           INT      NOT NULL,
DATA_CONSULTA           DATETIME,
CRM_MEDICO              INT,
CPF_PACIENTE            VARCHAR(15),
NUMERO_CONSULTORIO      INT,
                        CONSTRAINT PK_CONSULTA
						PRIMARY KEY(COD_CONSULTA),
						CONSTRAINT FK_CONSULTA_PACIENTE
						FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF),
						CONSTRAINT FK_CONSULTA_MEDICO
						FOREIGN KEY (CRM_MEDICO) REFERENCES MEDICO(CRM)
);

CREATE TABLE CONSULTORIO
(NUMERO_CONSULTORIO         INT    NOT NULL,
                            CONSTRAINT PK_CONSULTORIO
							PRIMARY KEY(NUMERO_CONSULTORIO)
);

ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CONSULTA_CONSULTORIO
FOREIGN KEY (NUMERO_CONSULTORIO) REFERENCES CONSULTORIO(NUMERO_CONSULTORIO);

CREATE TABLE TRIAGEM
(COD_TRIAGEM              INT       NOT NULL,
DATA_TRIAGEM              DATETIME,
CRM_MEDICO                INT,
COREN_ENFERMEIRO          INT,
COREN_TECNICO_ENFERMAGEM  INT,
CPF_PACIENTE              VARCHAR(15),
NUMERO_CONSULTORIO        INT,
                          CONSTRAINT PK_TRIAGEM
						  PRIMARY KEY(COD_TRIAGEM),
						  CONSTRAINT FK_TRIAGEM_MEDICO
						  FOREIGN KEY(CRM_MEDICO) REFERENCES MEDICO(CRM),
						  CONSTRAINT FK_TRIAGEM_ENFERMEIRO
						  FOREIGN KEY(COREN_ENFERMEIRO) REFERENCES ENFERMEIRO(COREN),
						  CONSTRAINT FK_TRIAGEM_TECNICO_ENFERMAGEM
						  FOREIGN KEY(COREN_TECNICO_ENFERMAGEM) REFERENCES TECNICO_ENFERMAGEM(COREN),
						  CONSTRAINT FK_TRIAGEM_PACIENTE
						  FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF),
						  CONSTRAINT FK_TRIAGEM_CONSULTORIO
						  FOREIGN KEY(NUMERO_CONSULTORIO) REFERENCES CONSULTORIO(NUMERO_CONSULTORIO)
);

CREATE TABLE OFICINA
(COD_OFICINA          INT          NOT NULL,
NOME_OFICINA          VARCHAR(100) NOT NULL,
                      CONSTRAINT PK_OFICINA
					  PRIMARY KEY(COD_OFICINA)
);

CREATE TABLE ORDEM_SERVICO
(COD_OS        INT           NOT NULL,
DESCRICAO      VARCHAR(8000) NOT NULL,
DATA_ABERTURA  DATETIME,
STATUS_OS      VARCHAR(20),
COD_USUARIO    VARCHAR(20),
COD_OFICINA    INT,
               CONSTRAINT PK_ORDEM_SERVICO
			   PRIMARY KEY(COD_OS),
			   CONSTRAINT FK_ORDEM_SERVICO
			   FOREIGN KEY(COD_OFICINA) REFERENCES OFICINA(COD_OFICINA)
);

CREATE TABLE ESTOQUE
(COD_ESTOQUE       INT          NOT NULL,
NOME_ESTOQUE       VARCHAR(100) NOT NULL,
                   CONSTRAINT PK_ESTOQUE
				   PRIMARY KEY(COD_ESTOQUE)
);

CREATE TABLE EMPRESA
(COD_EMPRESA      INT          NOT NULL,
NOME_EMPRESA      VARCHAR(100) NOT NULL,
                  CONSTRAINT PK_EMPRESA
				  PRIMARY KEY(COD_EMPRESA)
);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_EMPRESA
FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA);

CREATE TABLE USUARIO
(COD_USUARIO         VARCHAR(20)   UNIQUE NOT NULL,
MATRICULA            INT,
                     CONSTRAINT PK_USUARIO
					 PRIMARY KEY(COD_USUARIO),
					 CONSTRAINT FK_USUARIO_FUNCIONARIO
					 FOREIGN KEY(MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
);

ALTER TABLE ORDEM_SERVICO
ADD CONSTRAINT FK_ORDEM_SERVICO_USUARIO
FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(COD_USUARIO);

CREATE TABLE PAPEL
(COD_PAPEL   INT          NOT NULL,
NOME_PAPEL   VARCHAR(100) NOT NULL,
             CONSTRAINT PK_PAPEL
			 PRIMARY KEY(COD_PAPEL)
);

CREATE TABLE RAMAL
(NUMERO_RAMAL     INT         NOT NULL,
COD_SETOR         INT         NOT NULL,
COD_USUARIO       VARCHAR(20),
                  CONSTRAINT PK_RAMAL
				  PRIMARY KEY(NUMERO_RAMAL),
				  CONSTRAINT FK_RAMAL_SETOR
				  FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR),
				  CONSTRAINT FK_RAMAL_USUARIO
				  FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(COD_USUARIO)
);

CREATE TABLE PAINEL
(EST_PAINEL      VARCHAR(10) UNIQUE NOT NULL,
IP_PAINEL        VARCHAR(20) UNIQUE NOT NULL,
COD_SETOR        INT,
                 CONSTRAINT PK_PAINEL
				 PRIMARY KEY(EST_PAINEL, IP_PAINEL),
				 CONSTRAINT FK_PAINEL_SETOR
				 FOREIGN KEY(COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

CREATE TABLE POSTO
(COD_POSTO        INT          NOT NULL,
NOME_POSTO        VARCHAR(100) NOT NULL,
                  CONSTRAINT PK_POSTO
				  PRIMARY KEY(COD_POSTO)
);

CREATE TABLE GESTOR_FUNCIONARIO
(MATRICULA_GESTOR         INT     NOT NULL,
COD_SETOR                 INT     NOT NULL,
                          CONSTRAINT PK_GESTOR_FUNCIONARIO
						  PRIMARY KEY(MATRICULA_GESTOR, COD_SETOR),
						  FOREIGN KEY (MATRICULA_GESTOR) REFERENCES FUNCIONARIO(MATRICULA),
						  CONSTRAINT FK_GESTOR_FUNCIONARIO_SETOR
						  FOREIGN KEY (COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

CREATE TABLE COMPUTADOR
(PATRIMONIO          INT                  NOT NULL,
EST_COMPUTADOR       VARCHAR(10)   UNIQUE NOT NULL,
IP_COMPUTADOR        VARCHAR(20)   UNIQUE NOT NULL,
COD_SETOR            INT,
                     CONSTRAINT PK_COMPUTADOR
					 PRIMARY KEY(PATRIMONIO),
					 CONSTRAINT FK_COMPUTADOR_SETOR
					 FOREIGN KEY(COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

CREATE TABLE BEIRA_LEITO
(COD_BEIRA_LEITO        INT          NOT NULL,
EST_BEIRA_LEITO         VARCHAR(10),
IP_BEIRA_LEITO          VARCHAR(20),
                        CONSTRAINT PK_BEIRA_LEITO
						PRIMARY KEY(COD_BEIRA_LEITO),
						CONSTRAINT FK_BEIRA_LEITO_ESTACAO
						FOREIGN KEY(EST_BEIRA_LEITO) REFERENCES COMPUTADOR(EST_COMPUTADOR),
						CONSTRAINT FK_BEIRA_LEITO_COMPUTADOR
						FOREIGN KEY(IP_BEIRA_LEITO) REFERENCES COMPUTADOR(IP_COMPUTADOR)
);

CREATE TABLE IMPRESSORA
(PATRIMONIO          INT         NOT NULL,
IP_IMPRESSORA        VARCHAR(20) NOT NULL,
COD_SETOR            INT,
                     CONSTRAINT PK_IMPRESSORA
					 PRIMARY KEY(PATRIMONIO),
					 CONSTRAINT FK_IMPRESSORA_SETOR
					 FOREIGN KEY(COD_SETOR) REFERENCES SETOR(COD_SETOR)
);

CREATE TABLE PRODUTO
(COD_PRODUTO       INT          NOT NULL,
NOME_PRODUTO       VARCHAR(100) NOT NULL,
TIPO_PRODUTO       VARCHAR(100),
COD_ESTOQUE        INT,
                  CONSTRAINT PK_PRODUTO
				  PRIMARY KEY(COD_PRODUTO),
				  CONSTRAINT FK_PRODUTO_ESTOQUE
				  FOREIGN KEY(COD_ESTOQUE) REFERENCES ESTOQUE(COD_ESTOQUE)
);