use hospital;

insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();
insert into medico(mat_medico, cpf_medico, nome_medico, crm_medico, endereco_medico, data_nascimento, area_especializada, carga_horaria, salario, sexo) values();

insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();
insert into enfermeiro(mat_enfermeiro, cpf_enfermeiro, nome_enfermeiro, endereco_enfermeiro, data_nascimento, area_Especializada, carga_horaria, salario, sexo) values ();

insert into estagiario(mat_estagiario, cpf_Estagiario, nome_estagiario, endereco_Estagiario, data_nascimento, area_especializada, carga_horaria, salario, inst_ensino, cod_depart, sexo) values();
insert into estagiario(mat_estagiario, cpf_Estagiario, nome_estagiario, endereco_Estagiario, data_nascimento, area_especializada, carga_horaria, salario, inst_ensino, cod_depart, sexo) values();
insert into estagiario(mat_estagiario, cpf_Estagiario, nome_estagiario, endereco_Estagiario, data_nascimento, area_especializada, carga_horaria, salario, inst_ensino, cod_depart, sexo) values();
insert into estagiario(mat_estagiario, cpf_Estagiario, nome_estagiario, endereco_Estagiario, data_nascimento, area_especializada, carga_horaria, salario, inst_ensino, cod_depart, sexo) values();
insert into estagiario(mat_estagiario, cpf_Estagiario, nome_estagiario, endereco_Estagiario, data_nascimento, area_especializada, carga_horaria, salario, inst_ensino, cod_depart, sexo) values();
insert into estagiario(mat_estagiario, cpf_Estagiario, nome_estagiario, endereco_Estagiario, data_nascimento, area_especializada, carga_horaria, salario, inst_ensino, cod_depart, sexo) values();
insert into estagiario(mat_estagiario, cpf_Estagiario, nome_estagiario, endereco_Estagiario, data_nascimento, area_especializada, carga_horaria, salario, inst_ensino, cod_depart, sexo) values();
insert into estagiario(mat_estagiario, cpf_Estagiario, nome_estagiario, endereco_Estagiario, data_nascimento, area_especializada, carga_horaria, salario, inst_ensino, cod_depart, sexo) values();

insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();
insert into funcionario_servical(mat_funcionario, cpf_funcionario, nome_funcionario, cargo, endereco, data_nascimento, carga_horaria, salario, cod_Depart, sexo) values ();

insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();
insert into centro_cirurgico(cod_sala_cirur, numero_sala, local_sala) values ();

insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();
insert into consultorio(cod_sala_consul, numero_sala, local_sala) values ();

insert into departamento(cod_Depart, nome_depart, localizacao) values ();
insert into departamento(cod_Depart, nome_depart, localizacao) values ();
insert into departamento(cod_Depart, nome_depart, localizacao) values ();
insert into departamento(cod_Depart, nome_depart, localizacao) values ();
insert into departamento(cod_Depart, nome_depart, localizacao) values ();
insert into departamento(cod_Depart, nome_depart, localizacao) values ();
insert into departamento(cod_Depart, nome_depart, localizacao) values ();
insert into departamento(cod_Depart, nome_depart, localizacao) values ();
insert into departamento(cod_Depart, nome_depart, localizacao) values ();

insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();
insert into paciente(cod_paciente, cpf_paciente, nome_paciente, endereco_paciente, data_nascimento, sexo) values ();

insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();
insert into consulta(cod_consulta, data_consulta, tipo_consulta, cod_paciente, mat_medico, cod_Sala_consul) values ();

insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();
insert into cirurgia(cod_cirurgia, data_cirurgia, tipo_cirurgia, cod_Sala_cirur, cod_paciente, mat_medico) values ();

insert into pronto_socorro(cod_pronto_socorro, data_pronto_socorro, tipo_pronto_socorro, cod_paciente, mat_medico, mat_enfermeiro) values ();
insert into pronto_socorro(cod_pronto_socorro, data_pronto_socorro, tipo_pronto_socorro, cod_paciente, mat_medico, mat_enfermeiro) values ();
insert into pronto_socorro(cod_pronto_socorro, data_pronto_socorro, tipo_pronto_socorro, cod_paciente, mat_medico, mat_enfermeiro) values ();
insert into pronto_socorro(cod_pronto_socorro, data_pronto_socorro, tipo_pronto_socorro, cod_paciente, mat_medico, mat_enfermeiro) values ();
insert into pronto_socorro(cod_pronto_socorro, data_pronto_socorro, tipo_pronto_socorro, cod_paciente, mat_medico, mat_enfermeiro) values ();
insert into pronto_socorro(cod_pronto_socorro, data_pronto_socorro, tipo_pronto_socorro, cod_paciente, mat_medico, mat_enfermeiro) values ();

insert into exame(cod_Exame, data_Exame, tipo_Exame, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into exame(cod_Exame, data_Exame, tipo_Exame, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into exame(cod_Exame, data_Exame, tipo_Exame, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into exame(cod_Exame, data_Exame, tipo_Exame, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into exame(cod_Exame, data_Exame, tipo_Exame, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into exame(cod_Exame, data_Exame, tipo_Exame, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into exame(cod_Exame, data_Exame, tipo_Exame, cod_paciente, mat_enfermeiro, mat_medico) values ();

insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();
insert into uti(cod_uti, sala_uti, cod_paciente, mat_enfermeiro, mat_medico) values ();

